//! 默认区域种子数据：定义应用首次启动时写入数据库的默认区域配置
//!
//! 使用 [`DefaultRegion`] struct 替代原先的元组表示，提升可读性与可维护性。

use crate::models::scroll_mode;

/// 默认区域配置项
///
/// 对应 `region_config` 表的一条记录（不含 id、aspect_ratio、created_at、updated_at
/// 等运行时字段）。`aspect_ratio` 统一在 `insert_default_regions` 中以 `"16:9"` 写入，
/// 故不在此 struct 中。
#[derive(Debug, Clone)]
pub struct DefaultRegion {
    pub name: String,
    pub category: String,
    /// 大地图子地图名（如 "四号谷地"/"武陵"），仅 category="大地图" 时使用
    pub sub_map: Option<String>,
    pub scroll_mode: String,
    pub grid_rows: i32,
    pub grid_cols: i32,
    pub overlap_x: f64,
    pub overlap_y: f64,
    pub drag_x: i32,
    pub drag_y: i32,
    pub capture_region_x: f64,
    pub capture_region_y: f64,
    pub capture_offset_y: i32,
    /// 模板引用（如 "谷地-供能高地"）
    pub template_ref: Option<String>,
    pub target_w: i32,
    pub target_h: i32,
}

/// 默认区域配置列表
///
/// 返回所有内置区域：基建区域、大地图子区域、自定义。
/// 包含 8 个基建区域、6 个大地图四号谷地子区域、8 个大地图武陵子区域、1 个自定义区域。
pub fn default_regions() -> Vec<DefaultRegion> {
    vec![
        // 基建区域
        // 武陵-武陵城 (target: 10100 × 10200)
        DefaultRegion {
            name: "武陵-武陵城".to_string(),
            category: "武陵".to_string(),
            sub_map: None,
            scroll_mode: "0次".to_string(),
            grid_rows: 15,
            grid_cols: 9,
            overlap_x: 0.09,
            overlap_y: 0.01,
            drag_x: 826,
            drag_y: 523,
            capture_region_x: scroll_mode::CAPTURE_REGION_X,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 10100,
            target_h: 10200,
        },
        // 武陵-景玉谷 (target: 7200 × 7400)
        DefaultRegion {
            name: "武陵-景玉谷".to_string(),
            category: "武陵".to_string(),
            sub_map: None,
            scroll_mode: "0次".to_string(),
            grid_rows: 10,
            grid_cols: 6,
            overlap_x: 0.001,
            overlap_y: 0.01,
            drag_x: 903,
            drag_y: 522,
            capture_region_x: scroll_mode::CAPTURE_REGION_X,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 7200,
            target_h: 7400,
        },
        // 武陵-首敦 (target: 7200 × 7400)
        DefaultRegion {
            name: "武陵-首敦".to_string(),
            category: "武陵".to_string(),
            sub_map: None,
            scroll_mode: "0次".to_string(),
            grid_rows: 10,
            grid_cols: 6,
            overlap_x: 0.001,
            overlap_y: 0.01,
            drag_x: 903,
            drag_y: 522,
            capture_region_x: scroll_mode::CAPTURE_REGION_X,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 7200,
            target_h: 7400,
        },
        // 武陵-应龙关 (target: 7200 × 7400)
        DefaultRegion {
            name: "武陵-应龙关".to_string(),
            category: "武陵".to_string(),
            sub_map: None,
            scroll_mode: "0次".to_string(),
            grid_rows: 10,
            grid_cols: 6,
            overlap_x: 0.001,
            overlap_y: 0.01,
            drag_x: 903,
            drag_y: 522,
            capture_region_x: scroll_mode::CAPTURE_REGION_X,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 7200,
            target_h: 7400,
        },
        // 四号谷地-枢纽区 (target: 9200 × 9000)
        DefaultRegion {
            name: "四号谷地-枢纽区".to_string(),
            category: "四号谷地".to_string(),
            sub_map: None,
            scroll_mode: "0次".to_string(),
            grid_rows: 13,
            grid_cols: 8,
            overlap_x: 0.06,
            overlap_y: 0.01,
            drag_x: 851,
            drag_y: 522,
            capture_region_x: scroll_mode::CAPTURE_REGION_X,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 9200,
            target_h: 9000,
        },
        // 四号谷地-供能高地 (target: 6200 × 6400)
        DefaultRegion {
            name: "四号谷地-供能高地".to_string(),
            category: "四号谷地".to_string(),
            sub_map: None,
            scroll_mode: "0次".to_string(),
            grid_rows: 9,
            grid_cols: 5,
            overlap_x: 0.001,
            overlap_y: 0.008,
            drag_x: 905,
            drag_y: 524,
            capture_region_x: scroll_mode::CAPTURE_REGION_X,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 6200,
            target_h: 6400,
        },
        // 四号谷地-谷地通道 (target: 6200 × 6400)
        DefaultRegion {
            name: "四号谷地-谷地通道".to_string(),
            category: "四号谷地".to_string(),
            sub_map: None,
            scroll_mode: "0次".to_string(),
            grid_rows: 9,
            grid_cols: 5,
            overlap_x: 0.001,
            overlap_y: 0.008,
            drag_x: 905,
            drag_y: 524,
            capture_region_x: scroll_mode::CAPTURE_REGION_X,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 6200,
            target_h: 6400,
        },
        // 四号谷地-源石研究园 (target: 6200 × 6400)
        DefaultRegion {
            name: "四号谷地-源石研究园".to_string(),
            category: "四号谷地".to_string(),
            sub_map: None,
            scroll_mode: "0次".to_string(),
            grid_rows: 9,
            grid_cols: 5,
            overlap_x: 0.001,
            overlap_y: 0.008,
            drag_x: 905,
            drag_y: 524,
            capture_region_x: scroll_mode::CAPTURE_REGION_X,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 6200,
            target_h: 6400,
        },

        // 大地图子区域（独立于基建，专用截图比例 0.378/0.388，各区域网格不同）
        // 大地图-四号谷地 子区域
        DefaultRegion {
            name: "枢纽区".to_string(),
            category: "大地图".to_string(),
            sub_map: Some("四号谷地".to_string()),
            scroll_mode: "0次".to_string(),
            grid_rows: 12,
            grid_cols: 10,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X_LARGE_MAP,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y_LARGE_MAP,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },
        DefaultRegion {
            name: "谷地通道".to_string(),
            category: "大地图".to_string(),
            sub_map: Some("四号谷地".to_string()),
            scroll_mode: "0次".to_string(),
            grid_rows: 8,
            grid_cols: 6,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X_LARGE_MAP,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y_LARGE_MAP,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },
        DefaultRegion {
            name: "源石研究园".to_string(),
            category: "大地图".to_string(),
            sub_map: Some("四号谷地".to_string()),
            scroll_mode: "0次".to_string(),
            grid_rows: 10,
            grid_cols: 10,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X_LARGE_MAP,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y_LARGE_MAP,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },
        DefaultRegion {
            name: "阿伯莉采石场".to_string(),
            category: "大地图".to_string(),
            sub_map: Some("四号谷地".to_string()),
            scroll_mode: "0次".to_string(),
            grid_rows: 8,
            grid_cols: 5,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X_LARGE_MAP,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y_LARGE_MAP,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },
        DefaultRegion {
            name: "矿脉园区".to_string(),
            category: "大地图".to_string(),
            sub_map: Some("四号谷地".to_string()),
            scroll_mode: "0次".to_string(),
            grid_rows: 15,
            grid_cols: 8,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X_LARGE_MAP,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y_LARGE_MAP,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },
        DefaultRegion {
            name: "供能高地".to_string(),
            category: "大地图".to_string(),
            sub_map: Some("四号谷地".to_string()),
            scroll_mode: "0次".to_string(),
            grid_rows: 14,
            grid_cols: 8,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X_LARGE_MAP,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y_LARGE_MAP,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },
        // 大地图-武陵 子区域
        DefaultRegion {
            name: "武陵城".to_string(),
            category: "大地图".to_string(),
            sub_map: Some("武陵".to_string()),
            scroll_mode: "0次".to_string(),
            grid_rows: 27,
            grid_cols: 12,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X_LARGE_MAP,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y_LARGE_MAP,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },
        DefaultRegion {
            name: "景玉谷".to_string(),
            category: "大地图".to_string(),
            sub_map: Some("武陵".to_string()),
            scroll_mode: "0次".to_string(),
            grid_rows: 20,
            grid_cols: 9,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X_LARGE_MAP,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y_LARGE_MAP,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },
        DefaultRegion {
            name: "清波寨".to_string(),
            category: "大地图".to_string(),
            sub_map: Some("武陵".to_string()),
            scroll_mode: "0次".to_string(),
            grid_rows: 13,
            grid_cols: 6,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X_LARGE_MAP,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y_LARGE_MAP,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },
        DefaultRegion {
            name: "首敦".to_string(),
            category: "大地图".to_string(),
            sub_map: Some("武陵".to_string()),
            scroll_mode: "0次".to_string(),
            grid_rows: 18,
            grid_cols: 7,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X_LARGE_MAP,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y_LARGE_MAP,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },
        DefaultRegion {
            name: "藏剑谷".to_string(),
            category: "大地图".to_string(),
            sub_map: Some("武陵".to_string()),
            scroll_mode: "0次".to_string(),
            grid_rows: 12,
            grid_cols: 9,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X_LARGE_MAP,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y_LARGE_MAP,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },
        DefaultRegion {
            name: "试验园区".to_string(),
            category: "大地图".to_string(),
            sub_map: Some("武陵".to_string()),
            scroll_mode: "0次".to_string(),
            grid_rows: 10,
            grid_cols: 7,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X_LARGE_MAP,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y_LARGE_MAP,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },
        DefaultRegion {
            name: "应龙关".to_string(),
            category: "大地图".to_string(),
            sub_map: Some("武陵".to_string()),
            scroll_mode: "0次".to_string(),
            grid_rows: 12,
            grid_cols: 9,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X_LARGE_MAP,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y_LARGE_MAP,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },
        DefaultRegion {
            name: "北部禁区".to_string(),
            category: "大地图".to_string(),
            sub_map: Some("武陵".to_string()),
            scroll_mode: "0次".to_string(),
            grid_rows: 17,
            grid_cols: 12,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X_LARGE_MAP,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y_LARGE_MAP,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },

        // 自定义
        DefaultRegion {
            name: "自定义".to_string(),
            category: "自定义".to_string(),
            sub_map: None,
            scroll_mode: "0次".to_string(),
            grid_rows: 2,
            grid_cols: 2,
            overlap_x: 0.001,
            overlap_y: 0.001,
            drag_x: 905,
            drag_y: 525,
            capture_region_x: scroll_mode::CAPTURE_REGION_X,
            capture_region_y: scroll_mode::CAPTURE_REGION_Y,
            capture_offset_y: 0,
            template_ref: None,
            target_w: 0,
            target_h: 0,
        },
    ]
}
